server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;

    location = /holiday-planning {
        return 301 /holiday-planning
    }

    location /holiday-planning/ {
        try_files $uri /holiday-planning/index.html;
    }

    # Optional: cache static files aggressively
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires max;
        log_not_found off;
    }
}
